# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # MASTER BRANCH (v2)
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 10

  # LEGACY BRANCH (v1)
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "legacy"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "legacy"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "legacy"
    schedule:
      interval: "monthly"
