site_name: pfSense REST API Documentation
nav:
  - Home: index.md
  - Installation & Configuration: install_and_config.md
  - Swagger & OpenAPI: swagger_and_openapi.md
  - Authentication & Authorization: authentication_and_authorization.md
  - Queries & Filters: queries_and_filters.md
  - Working with Object IDs: working_with_object_ids.md
  - Working with HATEOAS: working_with_hateoas.md
  - Common Control Parameters: common_control_parameters.md
  - Limitations & FAQs: limitations_and_faqs.md
  - Glossary: glossary.md
theme:
  name: readthedocs
  features:
    - search
    - navigation.tabs
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
