site_name: pfSense REST API Guide
nav:
  - General:
    - Home: index.md
    - Installation & Configuration: INSTALL_AND_CONFIG.md
    - Swagger & OpenAPI: SWAGGER_AND_OPENAPI.md
    - Endpoints Types: ENDPOINT_TYPES.md
    - Authentication & Authorization: AUTHENTICATION_AND_AUTHORIZATION.md
    - Queries & Filters: QUERIES_AND_FILTERS.md
    - Working with Object IDs: WORKING_WITH_OBJECT_IDS.md
    - Working with HATEOAS: WORKING_WITH_HATEOAS.md
    - Common Control Parameters: COMMON_CONTROL_PARAMETERS.md
    - Limitations & FAQs: LIMITATIONS_AND_FAQS.md
    - Glossary: GLOSSARY.md
    - Contributing & Development: CONTRIBUTING.md
  - Advanced Topics:
      - Dispatchers & Caching: DISPATCHERS_AND_CACHING.md
      - Building Custom Authentication: BUILDING_CUSTOM_AUTH_CLASSES.md
      - Building Custom Query Filters: BUILDING_CUSTOM_QUERY_FILTER_CLASSES.md
theme:
  name: readthedocs
  features:
    - search
    - navigation.tabs
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
