name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "master"

# Commit SHAs may differ when trigger via pull request vs workflow_dispatch, ensure the correct commit is referenced.
env:
  commit_id: "${{ github.event.pull_request.head.sha || github.sha }}"
  build_version: "0.0_0-dev-${{ github.event.pull_request.head.sha || github.sha }}"

jobs:
  build_pkg:
    runs-on: self-hosted

    strategy:
      matrix:
        include:
          - freebsd_version: FreeBSD-14.0-CURRENT
            freebsd_id: freebsd14

    steps:
      - uses: actions/checkout@v4
      - name: Setup FreeBSD build VM
        run: |
          /usr/local/bin/VBoxManage controlvm ${{ matrix.freebsd_version }} poweroff || true
          /usr/local/bin/VBoxManage snapshot ${{ matrix.freebsd_version }} restore initial
          /usr/local/bin/VBoxManage startvm ${{ matrix.freebsd_version }} --type headless
          sleep 5

      - name: Build pfSense-pkg-RESTAPI on FreeBSD
        run: |
          /usr/bin/ssh -o StrictHostKeyChecking=no -o LogLevel=quiet ${{ matrix.freebsd_version }}.jaredhendrickson.com 'sudo pkill ntpd || true && sudo ntpdate pool.ntp.org || true'
          /usr/bin/ssh -o StrictHostKeyChecking=no -o LogLevel=quiet ${{ matrix.freebsd_version }}.jaredhendrickson.com 'sudo pkg-static install -y php81-extensions'
          /usr/local/bin/python3 tools/make_package.py --host ${{ matrix.freebsd_version }}.jaredhendrickson.com --branch ${{ env.commit_id }} --tag ${{ env.build_version }}-${{ matrix.freebsd_id }}

      - name: Teardown FreeBSD build VM
        if: "${{ always() }}"
        run: |
          /usr/local/bin/VBoxManage controlvm ${{ matrix.freebsd_version }} poweroff || true
          /usr/local/bin/VBoxManage snapshot ${{matrix.freebsd_version}} restore initial

      - uses: actions/upload-artifact@v4
        with:
          name: pfSense-pkg-RESTAPI-${{ env.build_version }}-${{ matrix.freebsd_id }}.pkg
          path: pfSense-pkg-RESTAPI-${{ env.build_version }}-${{ matrix.freebsd_id }}.pkg

  build_openapi:
    runs-on: self-hosted
    needs: [build_pkg]
    strategy:
      matrix:
        include:
          - pfsense_version: pfSense-2.7.2-RELEASE
            freebsd_id: freebsd14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pfSense-pkg-RESTAPI-${{ env.build_version }}-${{ matrix.freebsd_id }}.pkg
          path: pfSense-pkg-RESTAPI-${{ env.build_version }}-${{ matrix.freebsd_id }}.pkg

      - name: Setup pfSense VM
        run: |
          /usr/local/bin/VBoxManage controlvm ${{ matrix.pfsense_version }} poweroff || true
          /usr/local/bin/VBoxManage snapshot ${{ matrix.pfsense_version }} restore initial
          /usr/local/bin/VBoxManage startvm ${{ matrix.pfsense_version }} --type headless
          sleep 5

      # This is only necessary until GitHub Actions allows an easier way to get a URL to download the artifact within pfSense
      - name: Copy pfSense-pkg-RESTAPI build to pfSense
        run: |
          pfsense-vshell --host ${{ matrix.pfsense_version }}.jaredhendrickson.com -u admin -p pfsense -c 'pfSsh.php playback enablesshd' -k
          pfsense-vshell --host ${{ matrix.pfsense_version }}.jaredhendrickson.com -u admin -p pfsense -c "mkdir /root/.ssh/ && echo $(cat ~/.ssh/id_rsa.pub) > /root/.ssh/authorized_keys" -k
          scp -o StrictHostKeyChecking=no pfSense-pkg-RESTAPI-${{ env.build_version }}-${{ matrix.freebsd_id }}.pkg/pfSense-pkg-RESTAPI-${{ env.build_version }}-${{ matrix.freebsd_id }}.pkg admin@${{ matrix.pfsense_version }}.jaredhendrickson.com:/tmp/

      - name: Install pfSense-pkg-RESTAPI on pfSense
        run: |
          ssh -o StrictHostKeyChecking=no -o LogLevel=quiet admin@${{ matrix.pfsense_version }}.jaredhendrickson.com "pkg -C /dev/null add /tmp/pfSense-pkg-RESTAPI-${{ env.build_version }}-${{ matrix.freebsd_id }}.pkg"
          sleep 5

      - name: Fetch OpenAPI schema from pfSense
        run: curl -s -k -u admin:pfsense -X GET https://${{ matrix.pfsense_version }}.jaredhendrickson.com/api/v2/schema > openapi-${{ matrix.pfsense_version }}.json

      - name: Teardown pfSense VM
        if: "${{ always() }}"
        run: |
          /usr/local/bin/VBoxManage controlvm ${{ matrix.pfsense_version }} poweroff || true
          /usr/local/bin/VBoxManage snapshot ${{ matrix.pfsense_version }} restore initial

      - uses: actions/upload-artifact@v4
        with:
          name: openapi-${{ matrix.pfsense_version }}.json
          path: openapi-${{ matrix.pfsense_version }}.json

  check_openapi:
    runs-on: ubuntu-latest
    needs: [build_openapi]
    strategy:
      matrix:
        include:
          - pfsense_version: pfSense-2.7.2-RELEASE
            freebsd_id: freebsd14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: openapi-${{ matrix.pfsense_version }}.json
          path: openapi-${{ matrix.pfsense_version }}.json

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install npm dependencies
        run: npm i

      - name: Validate OpenAPI schema
        run: ./node_modules/.bin/spectral lint openapi-${{ matrix.pfsense_version }}.json/openapi-${{ matrix.pfsense_version }}.json --fail-severity warn

  check_tests:
    runs-on: self-hosted
    needs: [build_openapi]

    strategy:
      matrix:
        include:
          - pfsense_version: pfSense-2.7.2-RELEASE
            freebsd_id: freebsd14

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: pfSense-pkg-RESTAPI-${{ env.build_version }}-${{ matrix.freebsd_id }}.pkg
          path: pfSense-pkg-RESTAPI-${{ env.build_version }}-${{ matrix.freebsd_id }}.pkg

      - name: Setup pfSense VM
        run: |
          /usr/local/bin/VBoxManage controlvm ${{ matrix.pfsense_version }} poweroff || true
          /usr/local/bin/VBoxManage snapshot ${{ matrix.pfsense_version }} restore initial
          /usr/local/bin/VBoxManage startvm ${{ matrix.pfsense_version }} --type headless
          sleep 5

      # This is only necessary until GitHub Actions allows an easier way to get a URL to download the artifact within pfSense
      - name: Copy pfSense-pkg-RESTAPI build to pfSense
        run: |
          pfsense-vshell --host ${{ matrix.pfsense_version }}.jaredhendrickson.com -u admin -p pfsense -c 'pfSsh.php playback enablesshd' -k
          pfsense-vshell --host ${{ matrix.pfsense_version }}.jaredhendrickson.com -u admin -p pfsense -c "mkdir /root/.ssh/ && echo $(cat ~/.ssh/id_rsa.pub) > /root/.ssh/authorized_keys" -k
          scp -o StrictHostKeyChecking=no pfSense-pkg-RESTAPI-${{ env.build_version }}-${{ matrix.freebsd_id }}.pkg/pfSense-pkg-RESTAPI-${{ env.build_version }}-${{ matrix.freebsd_id }}.pkg admin@${{ matrix.pfsense_version }}.jaredhendrickson.com:/tmp/

      - name: Install pfSense-pkg-RESTAPI on pfSense
        run: |
          ssh -o StrictHostKeyChecking=no -o LogLevel=quiet admin@${{ matrix.pfsense_version }}.jaredhendrickson.com "pkg -C /dev/null add /tmp/pfSense-pkg-RESTAPI-${{ env.build_version }}-${{ matrix.freebsd_id }}.pkg"
          sleep 5

      - name: Run pfSense-pkg-RESTAPI tests
        run: |
          ssh -o StrictHostKeyChecking=no -o LogLevel=quiet admin@${{ matrix.pfsense_version }}.jaredhendrickson.com 'pfsense-restapi runtests'

      - name: Teardown pfSense VM
        if: "${{ always() }}"
        run: |
          /usr/local/bin/VBoxManage controlvm ${{ matrix.pfsense_version }} poweroff || true
          /usr/local/bin/VBoxManage snapshot ${{ matrix.pfsense_version }} restore initial
