name: Build

on: push

env:
  build_version: "0.0_0dev_${GITHUB_SHA}"
  
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          - freebsd_version: FreeBSD-14.0-CURRENT
            freebsd_ip: 192.168.55.14
    steps:
      - uses: actions/checkout@v3
      - name: Setup FreeBSD build VM
        run: |
          /usr/local/bin/vboxmanage controlvm ${matrix.freebsd_version} poweroff || true
          /usr/local/bin/vboxmanage snapshot ${matrix.freebsd_version} restore initial
          /usr/local/bin/vboxmanage startvm ${matrix.freebsd_version} --type headless
          sleep 5

      - name: Build pfSense-pkg-API on FreeBSD
        run: |
          /usr/bin/ssh ${matrix.freebsd_ip} 'sudo pkill ntpd || true && sudo ntpdate pool.ntp.org || true'
          /usr/local/bin/python3 tools/make_package.py --host ${matrix.freebsd_ip} --branch ${GITHUB_SHA} --tag ${env.build_version}

      - name: Teardown FreeBSD build VM
        run: |
          /usr/local/bin/vboxmanage controlvm ${matrix.freebsd_version} poweroff || true
          /usr/local/bin/vboxmanage snapshot ${matrix.freebsd_version} restore initial

      - uses: actions/upload-artifact@v3
        with:
          name: "pfSense-pkg-API-${env.build_version}.pkg"
          path: "pfSense-pkg-API-${env.build_version}.pkg"
