name: Build

on: push

env:
  build_version: "0.0_0dev_${{github.sha}}"
  
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        freebsd_version: [FreeBSD-14.0-CURRENT]
    steps:
      - uses: actions/checkout@v3
      - name: Setup FreeBSD build VM
        run: |
          "/usr/local/bin/VBoxManage controlvm ${{matrix.freebsd_version}} poweroff || true"
          "/usr/local/bin/VBoxManage snapshot ${{matrix.freebsd_version}} restore initial"
          "/usr/local/bin/VBoxManage startvm ${{matrix.freebsd_version}} --type headless"
          "sleep 5"

      - name: Build pfSense-pkg-API on FreeBSD
        run: |
          "/usr/bin/ssh ${{matrix.freebsd_version}}.jaredhendrickson.com 'sudo pkill ntpd || true && sudo ntpdate pool.ntp.org || true'"
          "/usr/local/bin/python3 tools/make_package.py --host ${{matrix.freebsd_version}}.jaredhendrickson.com --branch ${{github.sha}} --tag ${{env.build_version}}"

      - name: Teardown FreeBSD build VM
        run: |
          "/usr/local/bin/VBoxManage controlvm ${{matrix.freebsd_version}} poweroff || true"
          "/usr/local/bin/VBoxManage snapshot ${{matrix.freebsd_version}} restore initial"

      - uses: actions/upload-artifact@v3
        with:
          name: "pfSense-pkg-API-${{env.build_version}}.pkg"
          path: "pfSense-pkg-API-${{env.build_version}}.pkg"
