name: PHPLint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '7.2'
          - '7.4'
    steps:
      - uses: actions/checkout@v3
      - uses: firehed/lint-php-action@v1
        with:
          file-extensions: 'php, inc'
