name: PHPlint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint on PHP 8.1
        uses: firehed/lint-php-action@v1
        with:
          file-extensions: 'php, inc'
          php-version: "8.1"
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpstan@v3
        with:
          path: pfSense-pkg-API/files/
          php_version: 8.2
