name: Quality
on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm packages
        run: npm install
      - name: Check Prettier
        run: ./node_modules/.bin/prettier --check ./pfSense-pkg-RESTAPI/files

  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check PHP syntax errors
        uses: overtrue/phplint@9.0.3
        with:
          path: "./pfSense-pkg-RESTAPI/files/usr/local/pkg/RESTAPI/**/*.inc"

  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
